package com.example.transation.entity.bean;

import java.math.BigDecimal;
import java.util.Date;

public class SharesLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares_log.id
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares_log.share_num
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    private String shareNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares_log.price
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares_log.create_time
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares_log.update_time
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares_log.id
     *
     * @return the value of shares_log.id
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares_log.id
     *
     * @param id the value for shares_log.id
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares_log.share_num
     *
     * @return the value of shares_log.share_num
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    public String getShareNum() {
        return shareNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares_log.share_num
     *
     * @param shareNum the value for shares_log.share_num
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    public void setShareNum(String shareNum) {
        this.shareNum = shareNum == null ? null : shareNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares_log.price
     *
     * @return the value of shares_log.price
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares_log.price
     *
     * @param price the value for shares_log.price
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares_log.create_time
     *
     * @return the value of shares_log.create_time
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares_log.create_time
     *
     * @param createTime the value for shares_log.create_time
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares_log.update_time
     *
     * @return the value of shares_log.update_time
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares_log.update_time
     *
     * @param updateTime the value for shares_log.update_time
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}