package com.example.transation.entity.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Shares {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.id
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.num
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.name
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.predict_price
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    private BigDecimal predictPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.current_price
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    private BigDecimal currentPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.predict_percent
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    private BigDecimal predictPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.create_time
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares.update_time
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.id
     *
     * @return the value of shares.id
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.id
     *
     * @param id the value for shares.id
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.num
     *
     * @return the value of shares.num
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.num
     *
     * @param num the value for shares.num
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.name
     *
     * @return the value of shares.name
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.name
     *
     * @param name the value for shares.name
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.predict_price
     *
     * @return the value of shares.predict_price
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public BigDecimal getPredictPrice() {
        return predictPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.predict_price
     *
     * @param predictPrice the value for shares.predict_price
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public void setPredictPrice(BigDecimal predictPrice) {
        this.predictPrice = predictPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.current_price
     *
     * @return the value of shares.current_price
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public BigDecimal getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.current_price
     *
     * @param currentPrice the value for shares.current_price
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public void setCurrentPrice(BigDecimal currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.predict_percent
     *
     * @return the value of shares.predict_percent
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public BigDecimal getPredictPercent() {
        return predictPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.predict_percent
     *
     * @param predictPercent the value for shares.predict_percent
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public void setPredictPercent(BigDecimal predictPercent) {
        this.predictPercent = predictPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.create_time
     *
     * @return the value of shares.create_time
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.create_time
     *
     * @param createTime the value for shares.create_time
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares.update_time
     *
     * @return the value of shares.update_time
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares.update_time
     *
     * @param updateTime the value for shares.update_time
     *
     * @mbg.generated Sat Apr 25 16:15:31 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}