package com.example.transation.entity.bean;

import java.math.BigDecimal;
import java.util.Date;

public class TradeLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_log.id
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_log.share_num
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    private String shareNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_log.amount
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_log.create_time
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_log.update_time
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_log.type
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_log.cost_rmb
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    private BigDecimal costRmb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_log.operate_type
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    private Integer operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_log.user_id
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_log.id
     *
     * @return the value of trade_log.id
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_log.id
     *
     * @param id the value for trade_log.id
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_log.share_num
     *
     * @return the value of trade_log.share_num
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public String getShareNum() {
        return shareNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_log.share_num
     *
     * @param shareNum the value for trade_log.share_num
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public void setShareNum(String shareNum) {
        this.shareNum = shareNum == null ? null : shareNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_log.amount
     *
     * @return the value of trade_log.amount
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_log.amount
     *
     * @param amount the value for trade_log.amount
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_log.create_time
     *
     * @return the value of trade_log.create_time
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_log.create_time
     *
     * @param createTime the value for trade_log.create_time
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_log.update_time
     *
     * @return the value of trade_log.update_time
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_log.update_time
     *
     * @param updateTime the value for trade_log.update_time
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_log.type
     *
     * @return the value of trade_log.type
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_log.type
     *
     * @param type the value for trade_log.type
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_log.cost_rmb
     *
     * @return the value of trade_log.cost_rmb
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public BigDecimal getCostRmb() {
        return costRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_log.cost_rmb
     *
     * @param costRmb the value for trade_log.cost_rmb
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public void setCostRmb(BigDecimal costRmb) {
        this.costRmb = costRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_log.operate_type
     *
     * @return the value of trade_log.operate_type
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_log.operate_type
     *
     * @param operateType the value for trade_log.operate_type
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_log.user_id
     *
     * @return the value of trade_log.user_id
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_log.user_id
     *
     * @param userId the value for trade_log.user_id
     *
     * @mbg.generated Mon Apr 27 20:37:21 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}