package com.example.transation.mapper;

import com.example.transation.entity.bean.SharesLog;
import com.example.transation.entity.bean.SharesLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SharesLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    long countByExample(SharesLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    int deleteByExample(SharesLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    int insert(SharesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    int insertSelective(SharesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    List<SharesLog> selectByExample(SharesLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    SharesLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") SharesLog record, @Param("example") SharesLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    int updateByExample(@Param("record") SharesLog record, @Param("example") SharesLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    int updateByPrimaryKeySelective(SharesLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares_log
     *
     * @mbg.generated Sat Apr 25 14:27:08 CST 2020
     */
    int updateByPrimaryKey(SharesLog record);
}